Treat zero byte stream as a file.
miurahr/py7zr pull request #551
Opened 2023-12-17 05:55 UTC by diedmon

Ref to issue [#549](https://github.com/miurahr/py7zr/issues/549) and issue [#398](https://github.com/miurahr/py7zr/issues/398). This pull request will fix those issues by treating zero byte stream as a file.

2023-12-17 14:21 UTC, miurahr commented
@diedmon could you add or enable unit test which reproduce the case a PR fixed?

2023-12-17 18:09 UTC, diedmon commented
@miurahr I don't how to enable unit test, but I attached the test file in the attachment.

[test_empty_stream.zip](https://github.com/miurahr/py7zr/files/13697302/test_empty_stream.zip)

2024-01-27 03:15 UTC, miurahr commented
Please put your test in [test_archive.py](https://github.com/miurahr/py7zr/tree/master)/[tests](https://github.com/miurahr/py7zr/tree/master/tests/test_archive.py).

You need to use `tmp_path` fixture to make target file in temporary folder.
like `def test_something(tmp_path):`

2024-01-28 13:08 UTC, diedmon commented
Hi, @miurahr, thank you for your guide. I have updated the test_archive.py.

2024-01-29 09:43 UTC, miurahr commented
> tox: check
>   check: commands[0]> flake8 py7zr tests
>   tests/test_archive.py:1170:3: BLK100 Black would make changes.
>   tests/test_archive.py:1170:3: E111 indentation is not a multiple of 4
>   tests/test_archive.py:1171:43: E231 missing whitespace after ','
>   tests/test_archive.py:1172:7: E111 indentation is not a multiple of 4
>   tests/test_archive.py:1172:31: E231 missing whitespace after ','
>   tests/test_archive.py:1173:3: E722 do not use bare 'except'
>   tests/test_archive.py:1173:3: E111 indentation is not a multiple of 4

2024-01-31 13:21 UTC, diedmon commented
Thank you for your comment, I have corrected the mistakes.

2024-01-31 22:02 UTC, miurahr requested changes

2024-01-31 22:02 UTC, miurahr commented on tests/test_archive.py
> +        with py7zr.SevenZipFile(file="test.7z", mode="w") as archive:
```suggestion
        with py7zr.SevenZipFile(file=tmp_path / "test.7z", mode="w") as archive:
```

2024-01-31 22:46 UTC, miurahr commented on tests/test_archive.py
> +        pytest.fail("Exception raised")
Please add several assertions to check resulted archives.
There is not necessary to use try except block.

please learn from other tests. Please do not use `with` syntax but you can make test like

```
archive = py7zr.SevenZipFile(tmp_path / "test.7z", "w")
archive.writestr(data="", arcname="empty.txt")
# assertions here, following check archive has a ONE file
assert len(archive.files.files_list) == 1
# When call close(), SevenZipFile write data into disk.
archive.close()
# you can extract file with py7zr  here and check whether created file size is zero.
#
# check a created archive. try extract by p7zip command
p7zip_test(tmp_path / "test.7z")
```

2024-02-01 12:03 UTC, diedmon commented
Thanks for your comment, I didn't realize that pytest can handle the exception properly without try and except. Also, please note that since a zero byte stream is treated as a file, it won't have the "emptystream" attribute anymore.

2024-02-11 13:58 UTC, miurahr requested changes

2024-02-11 13:58 UTC, miurahr commented on tests/test_archive.py
> +    assert archive.header.files_info.files[0]['uncompressed'] == 0
```suggestion
    assert archive.header.files_info.files[0]["uncompressed"] == 0
```

2024-02-11 13:58 UTC, miurahr commented on tests/test_archive.py
> +
```suggestion
```

2024-03-02 02:12 UTC, miurahr approved these changes

2024-03-02 02:13 UTC, merged